spring:
  datasource:
    url: jdbc:mariadb://localhost:23306/oops-pawever
    username: ${DB_USER:oops-pawever}
    password: ${DB_PASSWORD}

cloud:
  ncp:
    credentials:
      access-key: dummy
      secret-key: dummy