-- 발자국 남기기 미션 54개 (추억 남기기 18 + 음성 녹음 18 + 마음 전하기 18)
-- 이미 같은 id가 있으면 새 내용으로 덮어써서, 항상 보낸 54개 데이터만 남김

INSERT INTO missions (id, category, name, description, action_guide, illustration_prompt, order_index) VALUES
(1, '추억 남기기', '홈파티 벌여주기', '맛있는 선물로 채우는 최고급 만찬', '아이가 평소 정말 먹고 싶어 했던 고기나 간식을 듬뿍 준비해 보세요. 맛있게 먹는 행복한 표정을 사진으로 꼭 기록해 주세요!', 'A happy dog/cat enthusiastically eating a large, delicious steak/fish meal, with its owner lovingly watching. The scene is warm and cozy, with soft lighting. Digital art, emotional, heartwarming.', 1),
(2, '추억 남기기', '인생네컷 찍기', '함께 웃는 얼굴을 네 컷에 담아요', '반려동물 동반 사진관을 방문해 아이를 꼭 껴안고 네 가지 포즈를 취해봅니다. 인화된 사진은 아이의 물건 상자에 소중히 보관하세요.', 'A person and their dog/cat taking a life four-cut style photo, showing genuine smiles and affection. The background is simple and bright. Cartoonish, cute, memorable.', 2),
(3, '추억 남기기', '발도장 만들기', '영원히 기억될 작은 발자국 남기기', '클레이를 준비해 아이의 발바닥을 부드럽게 눌러 찍어냅니다. 굳은 뒤 날짜와 이름을 적어 장식하면 평생 보관할 귀중품이 될 거예요.', 'A person gently pressing their dog''s/cat''s paw into soft clay to create a paw print, with a focus on the loving interaction and the texture of the clay. Realistic, tender moment, warm colors.', 3),
(4, '추억 남기기', '원없이 냄새 맡게 하기', '아이의 속도에 맞춘 느릿한 산책', '리드줄을 느슨하게 잡고 아이의 뒤를 따르기만 하세요. 아이가 충분히 냄새를 맡도록 기다려주는 산책을 영상으로도 담아보세요.', 'An elderly dog/cat and its owner walking slowly on a beautiful, familiar path lined with trees, bathed in soft sunlight. The owner is looking down with a gentle smile. Emotional, peaceful, serene.', 4),
(5, '추억 남기기', '털 뭉치 보관하기', '부드러운 온기를 유리병에 담아요', '정성껏 빗질하며 모은 아이의 털을 작은 유리병이나 펜던트에 담아보세요. 체취와 촉감이 그리운 날, 이 털 뭉치가 큰 힘이 될 거예요.', 'A person carefully collecting a small tuft of fur from their dog/cat, placing it into a delicate glass vial. The scene is intimate and filled with love. Soft focus, warm light, sentimental.', 5),
(6, '추억 남기기', '드라이브 스루', '바람을 가르며 즐기는 드라이브', '차 창문을 열고 바람을 즐기는 아이의 얼굴을 담아보세요. 눈을 찡그리거나 귀가 휘날리는 다양한 표정을 카메라에 기록해 둡니다.', 'A collection of custom-made pet merchandise, such as a mug with a dog''s face, a keychain with a cat''s name, and a t-shirt with a paw print, all beautifully displayed. Product photography style, clean, personalized.', 6),
(7, '추억 남기기', '하루 동안 시간 보내기', '온전히 서로에게만 집중하는 하루', '단 하루라도 디지털 기기를 멀리하고, 오로지 아이의 눈을 맞추고 쓰다듬으며 온기를 나눠보세요. 그 찰나의 순간을 기억하세요.', 'A person and their dog/cat looking deeply into each other''s eyes, conveying a strong bond and understanding. The background is blurred, focusing on their faces. Close-up, emotional, serene.', 7),
(8, '추억 남기기', '노을 같이 보기', '노을빛 아래 나누는 고마운 마음', '해 질 녘 언덕에 나란히 앉아 붉은 노을을 감상해 보세요. 함께 보낸 긴 세월에 대해 고마움을 전하면 아이도 분명 듣고 있을 거예요.', 'A person holding a soft, familiar blanket that belonged to their pet, gently smelling it with a wistful expression. The blanket shows signs of use but is cherished. Sentimental, soft lighting, comforting.', 8),
(9, '추억 남기기', '최고급 스파 시켜주기', '정성 가득한 마사지로 전하는 사랑', '따뜻한 수건으로 아이 몸을 감싸고 관절 부위를 조심스럽게 마사지해 주세요. 편안해진 아이의 표정에서 깊은 유대감을 느낄 수 있어요.', 'A person and their dog/cat sitting side-by-side, silhouetted against a breathtaking sunset/sunrise over a calm landscape. The atmosphere is peaceful and reflective. Serene, majestic, emotional.', 9),
(10, '추억 남기기', '장난감 쇼핑', '아이가 직접 고르는 마지막 선물', '아이가 코를 대거나 관심을 보이는 장난감을 하나 사주세요. 아이가 가장 즐거워하는 순간을 함께 공유하는 소중한 시간이 될 거예요.', 'A close-up, high-definition photo of a dog''s/cat''s paw pad, showing intricate details and softness. The lighting is gentle, highlighting the texture. Macro photography, cute, detailed.', 10),
(11, '추억 남기기', '꼬순내 깊이 맡기', '기억에 새기는 고유의 향기', '아이의 정수리나 발바닥 등 특유의 꼬순내를 깊게 들이마셔 보세요. 그때의 감정을 적어두면 기억이 흐려질 때 큰 도움이 됩니다.', 'A person and their dog/cat looking at a photo album filled with pictures of the pet growing up, sharing a tender moment. The album is open on their lap. Nostalgic, warm, storytelling.', 11),
(12, '추억 남기기', '추억 앨범 정주행', '사진첩을 넘기며 추억하는 소중한 날', '앨범 속 옛 사진들을 아이 옆에서 하나씩 넘겨보세요. 가장 마음에 드는 사진 3장을 골라 인화해 보는 것도 좋은 방법입니다.', 'A person sitting next to their dog/cat, gently stroking its head while reading a handwritten letter aloud. The pet is looking up at the owner with affection. Intimate, loving, peaceful.', 12),
(13, '추억 남기기', '신발 물어뜯기', '오늘만은 허락할게! 신나는 장난', '평소 아이가 탐냈던 물건을 마음껏 물어뜯게 해주세요. 금기를 깨고 행복하게 장난치는 아이의 생동감 넘치는 모습을 기록해 보세요.', 'A happy dog/cat playing with a brand new, brightly colored toy, its owner smiling in the background. The scene is playful and joyful. Vibrant, energetic, fun.', 13),
(14, '추억 남기기', '10분 동안 마주보기', '깊은 눈맞춤으로 나누는 마음의 대화', '서로 마주 앉아 10분간 눈을 바라보세요. 최대한 부드럽고 천천히, 길게 아이와 교감하며 말로 다 못할 사랑을 전해봅니다.', 'A person and their dog/cat enjoying a peaceful moment on a sandy beach at sunset, or in a lush forest. The pet is looking out at the scenery. Adventurous, serene, beautiful landscape.', 14),
(15, '추억 남기기', '냄새 보관하기', '아이의 흔적을 밀봉하여 보존하기', '자주 입던 옷이나 방석 등을 밀봉팩에 담아 보관하세요. 아이의 체취가 담긴 이 물건들이 나중에 큰 위로가 되어줄 거예요.', 'A close-up of a pet''s collar and ID tag, placed gently on a soft surface, symbolizing cherished memories. The tag is slightly worn but beloved. Sentimental, minimalist, warm tones.', 15),
(16, '추억 남기기', '초콜릿 공장', '처음이자 마지막으로 허락된 달콤함', '이별 직전, 독성 때문에 금지했던 초콜릿 한 조각을 선물해 보세요. 세상의 모든 맛을 경험하고 떠날 수 있게 배려해 주는 겁니다.', 'A montage of short video clips of a happy, energetic dog/cat playing, running, and interacting with its owner, compiled into a heartwarming video. Dynamic, joyful, lively.', 16),
(17, '추억 남기기', '굿즈 소스 확보', '미래를 위해 꼼꼼히 기록하는 모습', '아이의 앞, 옆, 뒷모습과 비문(코 무늬)을 정밀하게 촬영해 두세요. 나중에 인형이나 키링 등 굿즈를 제작할 때 중요한 자료가 됩니다.', 'A person and their dog/cat peacefully napping together on a cozy couch or bed, bathed in soft, natural light. The scene is tranquil and comforting. Serene, intimate, warm.', 17),
(18, '추억 남기기', '햇살 아래 낮잠', '따스한 볕 아래 나란히 누워 쉬기', '창가나 테라스에 매트를 깔고 아이와 나란히 누워보세요. 아무것도 하지 않아도 괜찮아요. 서로의 숨소리를 느끼는 것만으로 충분합니다.', 'A heartwarming scene of a person and their pet enjoying a special moment together, illustrating the mission. Emotional, loving, detailed.', 18),
(19, '음성 녹음', '새근새근 잠자는 숨소리', '평화로운 꿈나라, 아이의 숨결 담기', '아이가 깊이 잠들었을 때, 조용한 환경에서 스마트폰을 가까이 대고 규칙적인 숨소리를 녹음해 보세요.', NULL, 19),
(20, '음성 녹음', '드르렁 코 고는 소리', '귀여운 코골이는 우리 집 소음기', '아이가 코를 골며 단잠에 빠졌을 때, 그 정겨운 소리를 기록해 보세요. 아이의 존재감이 가장 잘 느껴질 거예요.', NULL, 20),
(21, '음성 녹음', '세상에서 가장 반가운 인사', '나를 환영해 주는 기쁜 목소리', '외출 후 돌아왔을 때 아이가 반가워하며 짖거나 야옹거리는 소리를 담아보세요. 언제 들어도 행복해지는 소리입니다.', NULL, 21),
(22, '음성 녹음', '생명의 심장 박동', '살아있음을 느끼는 생명의 리듬', '아이가 편안하게 누워있을 때 가슴에 귀를 대보세요. 콩닥콩닥 뛰는 심장 소리는 가장 고귀한 기록이 됩니다.', NULL, 22),
(23, '음성 녹음', '오도독 사료 ASMR', '맛있게 냠냠! 행복한 식사 시간', '사료를 오도독 씹어 먹거나 물을 할짝할짝 마시는 소리를 녹음해 보세요. 아이의 건강함이 느껴지는 소리입니다.', NULL, 23),
(24, '음성 녹음', '짤깍짤깍 발자국 소리', '다다다, 나를 향해 달려오는 소리', '마룻바닥에 발톱이 닿는 짤깍 소리나 복도를 뛰어오는 발자국 소리를 담아보세요. 집안의 활기를 기억하게 해줍니다.', NULL, 24),
(25, '음성 녹음', '행복의 가르릉(골골송)', '고롱고롱, 행복이 가득한 엔진 소리', '아이를 쓰다듬어줄 때 기분이 좋아 내는 가르릉 소리를 녹음해 보세요. 듣는 것만으로도 마음이 치유되는 소리예요.', NULL, 25),
(26, '음성 녹음', '하품할 때 귀여운 소리', '아함! 입을 크게 벌린 짧은 외침', '아이가 하품하는 찰나의 순간을 포착해 보세요. 하품 끝에 묻어 나오는 짧고 귀여운 신음 소리를 기록에 남깁니다.', NULL, 26),
(27, '음성 녹음', '간식 보채는 애교 소리', '맛있는 거 주세요! 간절한 조르기', '간식 봉지 소리에 반응하며 빨리 달라고 보채는 애교 섞인 소리를 담아보세요. 아이의 귀여운 고집이 느껴집니다.', NULL, 27),
(28, '음성 녹음', '장난감 삑삑이 소리', '삑삑! 신나게 노는 활기찬 에너지', '좋아하는 장난감을 물고 흔들 때 나는 삑삑 소리와 아이의 거친 숨소리를 함께 녹음하며 즐거운 시간을 기록하세요.', NULL, 28),
(29, '음성 녹음', '애틋한 기다림의 소리', '문 앞에서 나를 기다리던 마음', '문밖에서 인기척을 느끼고 낑낑대며 기다리는 아이의 소리를 담아보세요. 당신을 향한 아이의 깊은 사랑이 담겨있습니다.', NULL, 29),
(30, '음성 녹음', '꿈꾸는 잠꼬대 소리', '꿈속에선 무얼 하나요? 작은 웅얼거림', '자면서 발을 버둥거리거나 웅얼웅얼 잠꼬대하는 소리를 조용히 담아보세요. 아이가 무슨 꿈을 꾸는지 상상하게 됩니다.', NULL, 30),
(31, '음성 녹음', '다정한 대답 소리', '이름을 부르면 들려오는 예쁜 대답', '아이의 이름을 다정하게 불렀을 때, 고개를 갸웃하며 내는 대답 소리를 녹음해 보세요. 서로 소통하던 순간의 기록입니다.', NULL, 31),
(32, '음성 녹음', '챱챱 정성스러운 그루밍', '단장을 마쳐요, 챱챱 정성스러운 소리', '아이가 발바닥을 핥거나 몸을 단장하는 챱챱 소리를 기록해 보세요. 아이 특유의 습관이 묻어나는 소중한 소리입니다.', NULL, 32),
(33, '음성 녹음', '파닥파닥 몸 터는 소리', '시원하게 털어내는 귀 파닥임 소리', '목욕 후나 자고 일어나서 몸을 크게 털 때 귀가 파닥거리는 소리를 담아보세요. 아이의 생동감을 느낄 수 있습니다.', NULL, 33),
(34, '음성 녹음', '설렘 가득한 헥헥거림', '산책 가자! 설렘이 묻어나는 숨소리', '산책 준비를 할 때 흥분해서 내는 헥헥거림이나 낑낑 소리를 녹음해 보세요. 세상 밖으로 나가는 즐거움이 담겨있습니다.', NULL, 34),
(35, '음성 녹음', '탁탁탁 기분 좋은 꼬리 소리', '꼬리로 바닥을 치는 기쁨의 신호', '기분이 좋을 때 꼬리로 바닥이나 가구를 탁탁 치는 소리를 담아보세요. 말하지 않아도 느껴지는 아이의 행복 신호입니다.', NULL, 35),
(36, '음성 녹음', '산책 소리 녹음!', '산책 소리 녹음은 처음일 거예요', '산책 시간, 아이와 함께 달리거나 천천히 햇빛을 즐기는 순간을 녹음해보세요. 보호자님의 목소리가 나와도 좋아요.', NULL, 36),
(37, '마음 전하기', '고마워, 내게 와줘서', '사랑하는 마음을 담은 감사 인사', '아이를 쓰다듬으며 나에게 와줘서 고맙고, 함께해서 행복했다는 진심 어린 말을 녹음해 보세요.', NULL, 37),
(38, '마음 전하기', '내 인생 최고의 선물', '너를 만나 정말 행복했어', '아이 덕분에 내 인생이 얼마나 풍요롭고 기적 같았는지 이야기하는 감사 메시지를 담아보세요.', NULL, 38),
(39, '마음 전하기', '못다 전한 사과의 말', '미안했던 마음, 이젠 털어내요', '아이에게 해주지 못했던 것, 실수했던 일들을 솔직하게 말하며 미안한 마음을 전하고 용서를 구해봅니다.', NULL, 39),
(40, '마음 전하기', '무지개 다리 너머 안녕', '아프지 말고 마음껏 뛰어놀렴', '아이가 무지개 다리 너머에서 아픔 없이 평안하고 행복하게 지내기를 바라는 당부의 말을 남겨보세요.', NULL, 40),
(41, '마음 전하기', '다시 만날 그날의 약속', '우리 나중에 꼭 다시 만나자', '언젠가 다시 만날 것을 약속하며, 아이와 보호자 사이의 영원한 유대감을 목소리로 기록해 둡니다.', NULL, 41),
(42, '마음 전하기', '가장 소중한 이름 부르기', '다정하게 이름을 불러주세요', '아이의 이름을 여러 번 다정하게 부르며, 그 이름이 당신에게 얼마나 소중한 의미인지 이야기해 보세요.', NULL, 42),
(43, '마음 전하기', '가장 예뻤던 너의 모습', '눈부시게 사랑스럽던 순간들', '사진을 보며 가장 기억에 남는 예쁜 순간을 구체적으로 묘사해 보세요. 목소리에 그리움이 묻어날 거예요.', NULL, 43),
(44, '마음 전하기', '네가 내게 준 커다란 위로', '너 덕분에 견딜 수 있었어', '힘들었던 순간 아이가 옆에 있어주어 위로받았던 경험을 이야기하며, 아이에게 고마움을 전해봅니다.', NULL, 44),
(45, '마음 전하기', '사랑해, 사랑해, 사랑해', '열 번의 고백으로 전하는 진심', '아이에게 사랑한다는 말을 10번 반복해서 녹음해 보세요. 진심이 분명 아이에게 닿을 거예요.', NULL, 45),
(46, '마음 전하기', '우리만의 다정한 별명', '너만 아는 특별한 이름 부르기', '아이가 좋아했던 별명이나 둘만의 특별한 호칭을 다정하게 불러주며 소중했던 관계를 추억해 보세요.', NULL, 46),
(47, '마음 전하기', '꿈속에서 다시 만나자', '오늘 밤 꿈속에 꼭 나타나 줘', '꿈속에서라도 아이를 다시 만나고 싶은 간절한 마음을 전해보세요. 꿈에서 함께 보낼 시간을 약속합니다.', NULL, 47),
(48, '마음 전하기', '조금만 기다려 줄래?', '걱정하지 마, 나도 잘 지낼게', '아이를 먼저 보내는 미안함을 덜어내고, 보호자도 씩씩하게 잘 지낼 테니 걱정 말라는 안심을 전하세요.', NULL, 48),
(49, '마음 전하기', '너의 빈자리와 나의 다짐', '너를 기억하며 씩씩하게 살게', '아이의 빈자리를 어떻게 채워나갈지, 아이를 기억하며 앞으로 어떻게 살아갈지 스스로에게 하는 다짐을 남겨보세요.', NULL, 49),
(50, '마음 전하기', '영원히 잊지 않을게', '너의 기억을 소중히 간직할게', '아이를 영원히 잊지 않고, 함께한 모든 추억을 가슴속에 깊이 간직하겠다는 소중한 맹세를 녹음합니다.', NULL, 50),
(51, '마음 전하기', '아이에게 묻고 싶은 말', '너는 우리와 함께라 행복했니?', '나랑 살면서 정말 행복했니? 같이 평소 아이의 속마음이 궁금했던 점들을 다정하게 물어보는 시간입니다.', NULL, 51),
(52, '마음 전하기', '너를 처음 만난 날', '온도와 냄새까지 선명한 기억', '처음 아이를 품에 안았던 날의 온도, 인상, 풍경 등을 구체적으로 묘사하며 첫 만남의 설렘을 기록하세요.', NULL, 52),
(53, '마음 전하기', '너의 장난기 어린 모습', '당황스러웠지만 귀여웠던 장난', '집안을 어지럽히거나 간식을 얻으려 부렸던 꾀 등 아이만의 독특하고 귀여운 장난들을 추억하며 이야기해 보세요.', NULL, 53),
(54, '마음 전하기', '네가 남겨준 사랑의 유산', '더 많은 생명을 아껴줄게', '아이에게 받은 사랑을 세상의 다른 아픈 친구들에게도 나누며 살겠다는 따뜻한 다짐을 남겨보세요.', NULL, 54)
ON DUPLICATE KEY UPDATE category=VALUES(category), name=VALUES(name), description=VALUES(description), action_guide=VALUES(action_guide), illustration_prompt=VALUES(illustration_prompt), order_index=VALUES(order_index);
